apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-lens-agent
  namespace: eks-lens
spec:
  selector:
    matchLabels:
      app: eks-lens
      component: eks-lens-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: eks-lens
        component: eks-lens-agent
    spec:
      serviceAccountName: eks-lens-agent
      containers:
        - name: eks-lens-agent
          image: ghcr.io/doitintl/eks-lens-agent:latest
          args:
            - run
          env:
            - name: CLUSTER_NAME
              value: gaia-cost
            - name: STREAM_NAME
              value: eks-lens
            - name: LOG_LEVEL
              value: debug
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
      restartPolicy: Always
